### ISSUE TITLE
Nested dynamic menus

### ISSUE THREAD

**Issue by mmohammadi9812** [grammyjs/menu#17]
Hi

I'm trying to use this plugin, with _deno 1.18.2_ and _grammy 1.7.0_, and I don't know if this is feasible or not, but I wanted to have a nested menu in my dynamic menu

i.e. I fetch some data, create a menu with `dynamic`, and then if user clicked a button, I wanted to fetch another data and send another _dynamic_ menu. I tried to do this by `const mymenu = new Menu(name, ...` and then `ctx.reply(...., {reply_markup: mymenu})`, but it gives an error about `Did you forget to use bot.use()` 

Any help is appriciated

**Comment by KnorpelSenf** [comment]
You need to show the full code in order to illustrate the problem. Also consider providing only a reproduction example if your full code is too complex.

**Comment by mmohammadi9812** [comment]
Ok, this is my code:

```typescript
const m = new Menu<CustomContext>("menu1")
.dynamic(async (_, range) => {
  const a = await fetch("something").then((res) => res.json());

  for (const b of a) {
    range.text(a.name, (ctx) => {

      const n = new Menu<CustomContext>(b.name)
      .dynamic((_, rrange) => {
        for (const c of b.children) {
          rrange.text(c.name, (cctx) => {
            ...
          })
        }
      });

      ctx.reply(b.name, {reply_markup: n});
    }).row();

  }
});

```

and the error I'm getting is:

```text
error: Uncaught (in promise) Error: Cannot send menu '...'! Did you forget to use bot.use() for it?
```

**Comment by mmohammadi9812** [comment]
Ok, I think I fixed it, I added `m.register(n)` before `ctx.reply`, and now it works!

Closing this, and thanks for this great library!
