### ISSUE TITLE
feat: Allow `menu.url` to accept dynamic urls and text

### ISSUE THREAD

**Issue by yohanesyuen** [grammyjs/menu#26]
# Current Signature
```js
url(text: MaybeDynamicString<C>, url: string)
```

# Proposed Signature
```js
url(text: MaybeDynamicString<C>, url: MaybeDynamicString<C>)
```

**Comment by yohanesyuen** [comment]
@KnorpelSenf I notice that most of the functions takes the form ```func(text, ...middlewares)```. Will this feature require a rewrite of the core?

**Comment by KnorpelSenf** [comment]
> @KnorpelSenf I notice that most of the functions takes the form `func(text, ...middlewares)`. Will this feature require a rewrite of the core?

No. All we need to do is to also resolve `url` properties from the buttons, rather than just resolving the `text` properties.

**Comment by KnorpelSenf** [comment]
This needs to be done at https://github.com/grammyjs/menu/blob/a9818bfb35780ed5834c81e521b831753a92789e/src/menu.ts#L768 by calling `uniform` also for the URL.

**Comment by KnorpelSenf** [comment]
@yohanesyuen do you want to contribute back the changes?

**Comment by KnorpelSenf** [comment]
It seems like no one is willing to work on this. Note that you can already solve this problem using dynamic ranges. If anyone is willing to pick it up again, feel free to leave a comment. Closing.
