### ISSUE TITLE
feat: Menu navigation history

### ISSUE THREAD

**Issue by lexuzieel** [grammyjs/menu#37]
After discussion in the telegram channel it appears that currently `ctx.menu.back()` always returns to the top-most menu.
This makes it impossible to navigate menus up and down deeper than 2nd level.

In order to resolve this issue @KnorpelSenf suggested to use either payload or session for storing the data about previous menus.
I've opted to session storage since it was the most straight-forward for me 😊

The main caveat is that you have to rely on sessions and extend session data with a flavor, like this:

```ts
export type SessionData = {
    // Your custom session data here
} & NavigationHistorySessionFlavor;
```

I've put up a gist with the draft of the middleware: https://gist.github.com/MajorLettuce/2673f9a15fa1d8ab3e3078aa524650a4

Sample usage is as follows:

```ts
import { history } from "./utils/history";

const main = new Menu("main")
// Add "main" menu to the history stack
.submenu("Go to submenu1", "submenu1", history.add("main"));

const submenu1 = new Menu("submenu1")
// Pop "main" menu from the stack and navigate back to it
.text("Back", history.back);
.row()
// Add "submenu1" menu to the history stack
.submenu("Go to submenu 2", "submenu2", history.add("submenu1"));

const submenu2 = new Menu("submenu2")
// Pop "submenu1" menu from the stack and navigate back to it
.text("Back", history.back);

main.register([submenu1, submenu2]);
```

Will it possibly make sense to add it as part of the plugin?

**Comment by KnorpelSenf** [comment]
That's a pretty clean API, I like it. Adding things to the history is something that could be done internally without explicitly pushing entries.

So perhaps we need a session mode of the menu? `new Menu("id", { session: true })`?

How are we going to disambiguate between the existing back buttons and the navigation along the persisted history? Perhaps by adding new buttons which work similarly to the browser API for navigating? I'm not sure if it's a good design to change the behaviour of back buttons depending on the setting

**Comment by MajorLettuce** [comment]
Hmm, maybe we could add `history` option: `new Menu("id", { history: true })` which would change the behavior of the `back()` and `submenu()` methods by adding middleware to those. This will assume the usage of the session plugin.

For the history to work properly all child menus should also have this option enabled, otherwise it would break things. Maybe it's possible to set it implicitly when calling `register()` on the parent menu? Then setting it just for the parent menu would be sufficient, however that might be a bit too "magic".

**Comment by KnorpelSenf** [comment]
> Sure, I will fiddle around with it when I get time.

Is this still on your mind?

**Comment by KnorpelSenf** [comment]
I am no longer comfortable with building plugins that depend on other plugins, not even built-in ones like the session plugin. Also, there seems to be very little demand for this. Closing.

Please comment below if you want to add anything to the discussion or if you need this to be picked up again.
