### ISSUE TITLE
 Did you forget to use bot.use() for it? - Problem

### ISSUE THREAD

**Issue by MuratKaragozgil** [grammyjs/menu#44]
Hello Guys,

Let me explain the problem.

I have a few menus and I'm sure I registered them with the bot. Because I'm already using it for some logic and it works. The bad thing is that when I use these menus in bot.api.sendMessage() they do not work.
They work when I use ctx.reply(). What is the reason of this ?

**Working**
```typescript
await ctx.reply(ctx.t("start"), {
 reply_markup: this.menuService.getNewChannelTitleMenu(),
});
```

**Not Working**
```typescript
await bot.api.sendMessage(process.env.SUPER_ADMIN_ID, "test", {
 reply_markup: menuService.getNewChannelTitleMenu(),
});
```

**Comment by KnorpelSenf** [comment]
Menus are rendered based on context objects. If there's no context object, there's no way to render it.

You can send it via `ctx.api` instead of `bot.api`: https://grammy.dev/guide/context#available-actions

**Comment by MuratKaragozgil** [comment]
Thank you so much, it worked!!

**Comment by MuratKaragozgil** [comment]
Solved

**Comment by KnorpelSenf** [comment]
Awesome! 🎉

**Comment by JakubGrzegowski** [comment]
Hello, is there any workaround possible for sending menu without ctx? I'm stuck on finding a way to periodically send updated menu to x users (have only users id's stored atm)

**Comment by KnorpelSenf** [comment]
You can send inline keyboards instead of menus. There's a built-in plugin for that.
