### ISSUE TITLE
Process exit on button click spam (dynamic)

### ISSUE THREAD

**Issue by yogaajs** [grammyjs/menu#51]
Hi, I have nested menu

Menu A
- Button 1
- Button 2

Menu B
- Button 1
- Button 2

Menu C
- Button 1
- Button 2

On Button 1 (Menu A) click, it change the message of Menu A and show Menu B, same for Menu C.
I export all my menu and register on the main root Menu. 

**Problem:** When I spam click button on Menu C, there is the error **"GrammyError: Call to 'editMessageReplyMarkup' failed!"**

I can't find a way to handle this. Nothings works: Bot.catch, try catch on Dynamic function, try catch in toggle function  and try catch directly on range function handler.

This is my Menu C. When I remove the status emoji, it works. I know the problem is the menu update, if nothing change it throw an error, but how to avoid process exit ? Or avoid update if menu is the same.

`

    const menu = new Menu<ContextWithPayload>(MENU, { autoAnswer: false });
    
    menu.dynamic(async (ctx, range) => {
        try {
          const document = await filters.get(ctx.payload.chatId);
          if (!document) { return range; }
          for (const key in data) {
            const element = data[key as keyof typeof data];
            const statusEmoji = document['methods'].includes(element.id) ? '🟢' : '🔴';
            range.text(
              `${element.name} ${statusEmoji}`, 
              async (ctx) => { 
                await toggle(ctx, element.id);
                await ctx.menu.update({ immediate: true });
              }
            );
          }
          return range;           
        } catch (error) {
          console.log(error)
        }
    })
    
    menu.text("↓ Close", (ctx) => handleClose(ctx));
    
    export default menu;
`

**Comment by KnorpelSenf** [comment]
The process always exits if a promise rejects without a catch handler instead and without being `await`ed. The above code doesn't have this mistake. Also, note that it doesn't call `editMessageReplyMarkup`. It only installs a callback as a button handler, so the method will be invoked later during a middleware pass.

Most likely, you forgot to use `await` in a call to `next` somewhere. Double-check middleware your wrote yourself and installed upstream of the menu.

**Comment by yogaajs** [comment]
Oh god thank you so much! I spent the day looking. My middleware which I use to add a payload to the message created this problem

`
  const payload = async (ctx: ContextWithPayload | (ContextWithPayload & MenuFlavor), next: NextFunction): Promise<void> => {
      try {
          ... PROCESS
  
          // Attach the payload to the context if all data is valid
          ctx['payload'] = data;
  
          // Proceed to the next middleware or handler
          await next();       
  
      } catch (error) {
          console.error("[grammy][middlewares][payload]", error);
      }
  }
`
